name: CI

on:
  push:
    branches:
      - '*'

jobs:
  docker-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: docker://ghcr.io/hadolint/hadolint
        with:
          entrypoint: hadolint
          args: Dockerfile
